### Categories will be assigned to accessory slots in encounter order.
# Nodes in <> are optional.
##  Format:
#   {id}:
#     <name>: {name} # Defaults to {id}
#     <placeholder>:
#       material: {material} # Defaults to STONE
#       display-name: {display-name} # Defaults to "<name>"
#       custom-model-data: {custom-model-data} # Defaults to 1
#       lore: # Defaults to ["No <name> Activated"]
#       - {lore1}
#       - {lore2}
categories:
  robot:
    name: Robot
  backpack:
    name: Backpack
  rectangle:
    name: Rectangle
  ring:
    name: Ring
