name: Accessories
version: '${project.version}'
main: io.github.ms5984.retrox.accessories.internal.AccessoriesPlugin
api-version: 1.19
authors: [ ms5984 ]
description: ${project.description}
libraries:
  - "io.github.ms5984.libraries:tag-lib:${tagLibVersion}"
  - "org.jetbrains.kotlin:kotlin-stdlib:${project.kotlinVersion}"
