name: update-dependency-graph
on:
  workflow_dispatch:

jobs:
  build:
    name: Dependencies
    runs-on: ubuntu-latest
    permissions: # The Dependency Submission API requires write permission
      contents: write
    steps:
      - name: 'Checkout Repository'
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2.3.3

      - name: Gradle Dependency Submission
        uses: mikepenz/gradle-dependency-submission@v0.8.3
        with:
          gradle-build-module: |-
            :api
            :impl
          sub-module-mode: INDIVIDUAL
